### ISSUE TITLE
1.1.0版本 配置管理  点击发布按钮前端异常

### ISSUE THREAD

**Issue by niuchen** [polarismesh/femas#293]
1.1.0版本 配置管理  点击发布按钮
Uncaught ReferenceError: diff_match_patch is not defined
    at i (sct.js:7:15634)
    at b.init (sct.js:7:4544)
    at new g.MergeView (sct.js:7:14197)
    at g.MergeView (sct.js:7:13438)
    at sct.js:352:1775562
    at cu (sct.js:319:102665)
    at s.unstable_runWithPriority (sct.js:352:3692)
    at Vo (sct.js:319:43670)
    at su (sct.js:319:102223)
    at Ks (sct.js:319:87023)

**Comment by rottenmu** [comment]
稍等哈，找前端同学看下
